name: learn-github-actions
on:
  push:
    branches:
      - main

jobs:
  my_first_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: |
          echo "Hello, world"

      - name: run python script
        run: |
           pip install -r requirements.txt
           python ci.py
