on: push

jobs:
  sec:
    runs-on: ubuntu-latest
    steps:
    - run: |
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python
      env:
        MY_VAR: ${{ sec.secrets }}
        
